# Unix submit description file
# sleep.sub -- simple sleep job

universe                = grid
executable              = sleep.sh
log                     = sleep.log
output                  = outfile.txt
error                   = errors.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
use_x509userproxy = true
#+WantJobRouter = true
+TransferOutput = ""
grid_resource = condor simple-condor-ce.cern.ch simple-condor-ce.cern.ch:9619
queue
